create table if not exists public.buyer_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  lead_type text not null default 'business' check (lead_type in ('business','community','individual')),
  platform text,
  url text,
  location text,
  wanted_items text,
  contact_method text,
  contact_value text,
  notes text,
  priority text not null default 'WATCH' check (priority in ('STRONG','ACTIVE','WATCH')),
  status text not null default 'new' check (status in ('new','contacted','interested','passed','sold')),
  source_posted_at timestamptz,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.buyer_leads enable row level security;

create index if not exists buyer_leads_priority_idx on public.buyer_leads(priority);
create index if not exists buyer_leads_status_idx on public.buyer_leads(status);
create index if not exists buyer_leads_checked_at_idx on public.buyer_leads(checked_at desc);

insert into public.buyer_leads
  (name, lead_type, platform, url, location, wanted_items, contact_method, contact_value, notes, priority, status, source_posted_at, checked_at)
select *
from (values
  ('Bounty Hunter Toys','business','Local buyer','https://bountyhuntertoys.com/pages/what-we-buy','Hamilton, Ontario','Transformers Generation One (1984–1990); Masters of the Universe (1982–1987); other vintage toys','Phone','905-312-1621','Direct local buyer. Their current buying page explicitly lists G1 Transformers and vintage MOTU.','STRONG','new',null::timestamptz,now()),
  ('Thee Collector','business','Local collector/dealer','https://theecollector.ca/','Hamilton, Ontario','Vintage toys from the 1960s–1990s including Transformers, He-Man, G.I. Joe, robots and unusual toys','Email / Phone','info@theecollector.ca · 905-929-8697','Direct Hamilton buyer. Website states that buying vintage collections is a major part of the business.','STRONG','new',null::timestamptz,now()),
  ('Retrosaurus','business','Local buyer / trade','https://www.retrosaurus.ca/','Hamilton, Ontario','Vintage toys, collectibles, video games and related retro inventory','Phone / Website','289-682-8697','Local shop explicitly invites people with items to sell or trade to contact them.','ACTIVE','new',null::timestamptz,now()),
  ('Cybertron.ca Wanted Items','community','Collector forum','https://www.cybertron.ca/boards/forumdisplay.php?f=29','Canada','Transformers wanted posts, including G1 figures and G1 accessories','Forum','Cybertron.ca Marketplace','Canadian Transformers marketplace with an active Wanted Items section. Good place to match individual G1 parts to collectors.','ACTIVE','new',null::timestamptz,now()),
  ('HE-MANIA Community Buy Sell & Trade','community','Collector forum','https://he-mania.com/community/buy-sell/','Online','Masters of the Universe figures, playsets, vehicles and accessories','Forum','HE-MANIA.com','Active MOTU-specific buy/sell/trade community. Useful for Snake Mountain, figures, vehicles and loose accessories.','ACTIVE','new',null::timestamptz,now()),
  ('MOTU wanted buyer - Rochester Craigslist','individual','Craigslist','https://rochester.craigslist.org/wan/d/rochester-wanted-masters-of-the/7931087309.html','Rochester, New York','Anything Masters of the Universe: toys, figures, vehicles, playsets and other collectibles','Craigslist reply','Reply through listing','Direct wanted ad posted April 29, 2026 and updated May 11, 2026. Cross-border lead; verify the post is still active before contacting.','WATCH','new','2026-04-29T21:34:00-04:00'::timestamptz,now())
) as seed(name, lead_type, platform, url, location, wanted_items, contact_method, contact_value, notes, priority, status, source_posted_at, checked_at)
where not exists (
  select 1 from public.buyer_leads existing
  where existing.name = seed.name and coalesce(existing.url,'') = coalesce(seed.url,'')
);
