export const JUSTCONSIGNIN_PAGES = [
  {
    id: 'home',
    title: 'Home',
    path: '/',
    source: 'src/website/pages/Home/Home.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Homepage with Shopify positioning, workflow highlights, videos and site links.',
  },
  {
    id: 'features',
    title: 'Features',
    path: '/features',
    source: 'src/website/pages/Features/Features.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Feature overview and store-type sections.',
  },
  {
    id: 'how-it-works',
    title: 'How It Works',
    path: '/how-it-works',
    source: 'src/website/pages/HowItWorks/HowItWorks.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Six-step intake-to-payout workflow and problem/solution content.',
  },
  {
    id: 'pricing',
    title: 'Pricing',
    path: '/pricing',
    source: 'src/website/pages/Pricing/Pricing.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Trial, plan details and pricing feature lists.',
  },
  {
    id: 'faq',
    title: 'FAQ',
    path: '/faq',
    source: 'src/website/pages/FAQ/FAQ.jsx',
    kind: 'structured',
    editor: 'custom',
    description: 'FAQ groups plus FAQPage structured data.',
  },
  {
    id: 'blog',
    title: 'Blog',
    path: '/blog',
    source: 'src/website/pages/Blog/Blog.jsx',
    kind: 'content',
    editor: 'blog',
    description: 'Blog index. Individual posts continue to be managed under Blog Posts.',
  },
  {
    id: 'contact',
    title: 'Contact',
    path: '/contact',
    source: 'src/website/pages/Contact/Contact.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Support contact information and help instructions.',
  },
  {
    id: 'partner-program',
    title: 'Founding Partner Program',
    path: '/partner-program',
    aliases: ['/beta'],
    source: 'src/website/pages/Beta/Beta.jsx',
    kind: 'form',
    editor: 'custom',
    description: 'Founding Partner / beta landing page and application form.',
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    path: '/privacy',
    source: 'src/website/pages/Legal/Privacy.jsx',
    kind: 'legal',
    editor: 'visual',
    description: 'Public privacy policy.',
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    path: '/terms',
    source: 'src/website/pages/Legal/Terms.jsx',
    kind: 'legal',
    editor: 'visual',
    description: 'Public terms of service.',
  },
  {
    id: 'shopify-app',
    title: 'Shopify App Demo',
    path: '/shopify-app',
    aliases: ['/demo → /shopify-app'],
    source: 'src/website/demo-app/ShopifyAppPreview.jsx',
    kind: 'application',
    editor: 'custom',
    description: 'Interactive Shopify app demo. This is application UI rather than a normal marketing page.',
  },
];

export const JUSTINDEMATTEIS_PAGES = [
  {
    id: 'home',
    title: 'Home',
    path: '/',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    description: 'Portfolio homepage with positioning, featured work and calls to action.',
  },
  {
    id: 'work',
    title: 'Work',
    path: '/work',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    description: 'Projects and case studies.',
  },
  {
    id: 'ai-development',
    title: 'AI + Development',
    path: '/ai-development',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    description: 'How AI is used as part of the development and problem-solving workflow.',
  },
  {
    id: 'about',
    title: 'About',
    path: '/about',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    description: 'Career story, engineering background and transition into software development.',
  },
  {
    id: 'experience',
    title: 'Experience',
    path: '/experience',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    description: 'Professional experience, skills and technology.',
  },
  {
    id: 'blog',
    title: 'Blog',
    path: '/blog',
    source: 'shared blog manager',
    kind: 'content',
    editor: 'blog',
    description: 'Articles and development notes for the portfolio.',
  },
  {
    id: 'contact',
    title: 'Contact',
    path: '/contact',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    description: 'Employment, freelance and collaboration contact page.',
  },
];

export const WEBSITE_PAGES = JUSTCONSIGNIN_PAGES;

export function getWebsitePages(siteKey = 'justconsignin') {
  return siteKey === 'justindematteis' ? JUSTINDEMATTEIS_PAGES : JUSTCONSIGNIN_PAGES;
}

export function getWebsitePage(id, siteKey = 'justconsignin') {
  return getWebsitePages(siteKey).find(page => page.id === id) || null;
}

export function livePageUrl(path, siteKey = 'justconsignin') {
  const domain = siteKey === 'justindematteis' ? 'justindematteis.com' : 'justconsignin.com';
  return `https://www.${domain}${path === '/' ? '' : path}`;
}


const block = (type, id, props) => ({ type, props: { id, ...props } });
const heading = (id, text, level = 'h2') => block('HeadingBlock', id, { text, level, align: 'left' });
const text = (id, value) => block('TextBlock', id, { text: value, align: 'left' });
const hero = (id, eyebrow, headingText, body) => block('HeroBlock', id, {
  eyebrow,
  heading: headingText,
  text: body,
  image: '',
  imageAlt: '',
  buttonText: '',
  buttonUrl: '',
  background: 'light',
});
const cta = (id, headingText, body, buttonText, buttonUrl) => block('CtaBlock', id, {
  heading: headingText,
  text: body,
  buttonText,
  buttonUrl,
  background: 'dark',
});

const PAGE_EDITOR_DATA = {
  home: {
    content: [
      block('HomeHeroBlock', 'home-hero', {
        brandText: 'Consignment management built for Shopify stores',
        eyebrow: 'JustConsignIn for Shopify',
        heading: 'Create consignment products from your phone and sell them through Shopify.',
        text: 'JustConsignIn connects consignors, inventory, Shopify products, POS sales and payouts in one workflow — without spreadsheets or duplicate entry.',
        primaryButtonText: 'Open Shopify app demo',
        primaryButtonUrl: '/shopify-app',
        watchButtonText: 'Watch videos',
        watchButtonUrl: '#home-video-heading',
        partnerButtonText: 'Founding Partner Program',
        partnerButtonUrl: '/partner-program',
        note1: 'Create products from your phone',
        note2: 'Shopify POS ready',
        note3: 'Track consignor payouts',
        panelTitle: 'Shopify connected',
        panelSubtitle: 'Products · POS · Consignment',
        panelDate: 'Today',
        panelHeading: 'Consignment overview',
        metric1Label: 'Consignors',
        metric1Value: '24',
        metric2Label: 'Available items',
        metric2Value: '118',
        metric3Label: 'Sales',
        metric3Value: '$3,840',
        metric4Label: 'Owed',
        metric4Value: '$1,426',
        person1Initials: 'SM',
        person1Name: 'Sarah Miller',
        person1Detail: '4 items · $84.00 due',
        person1Percent: '60%',
        person2Initials: 'DR',
        person2Name: 'Daniel Reed',
        person2Detail: '2 items · $35.00 due',
        person2Percent: '50%',
      }),
      block('HomeIntegrationBlock', 'home-shopify', {
        eyebrow: 'Built around Shopify',
        heading: 'Intake, product creation and POS in one consignment workflow.',
        text: 'Use JustConsignIn to manage the consignment details Shopify does not track on its own, while keeping the product and sale inside your Shopify workflow.',
        card1Heading: 'Create Shopify products from your phone',
        card1Text: 'Enter the consignor and item once, add the product details and photo, then create the Shopify product directly from intake.',
        card2Heading: 'Sell consignment items at the point of sale',
        card2Text: 'Publish items to Shopify POS and keep the consignment item tied back to the correct consignor when it sells.',
        card3Heading: 'Know exactly what each consignor is owed',
        card3Text: 'Track sold-unpaid items, commission splits, payouts and transaction history without maintaining a second spreadsheet.',
      }),
      block('HomeVideosBlock', 'home-videos', {
        eyebrow: 'Watch the Shopify workflow',
        heading: 'See JustConsignIn in action.',
      }),
      block('HomeLinksBlock', 'home-links', {
        link1Title: 'Shopify features',
        link1Text: 'Products, POS, consignors, sales, payouts and reporting.',
        link1Url: '/features',
        link2Title: 'How it works',
        link2Text: 'Follow the Shopify consignment workflow from intake through payout.',
        link2Url: '/how-it-works',
        link3Title: 'Open the Shopify app demo',
        link3Text: 'Explore the JustConsignIn interface and connected workflow.',
        link3Url: '/shopify-app',
      }),
    ],
    root: { props: {} },
  },

  features: {
    content: [
      block('FeaturesHeroBlock', 'features-hero', {
        brandText: 'Built for Shopify consignment stores',
        eyebrow: 'Features',
        heading: 'Move consignment inventory from intake to sale faster.',
        text: 'JustConsignIn is built for Shopify store owners who process lots of unique consignment and resale inventory. Enter items quickly, create Shopify products without duplicate entry, track every sale back to the correct consignor and keep payouts organized in one workflow.',
        image: '',
        imageAlt: '',
        imagePosition: 'right',
      }),
      block('FeaturesGridBlock', 'features-grid', {
        eyebrow: 'Made for real resale workflows',
        heading: 'When every item is different, intake speed matters.',
        text: 'Traditional retail receives repeatable SKUs from suppliers. Consignment and resale stores often receive one-of-a-kind items in batches. JustConsignIn focuses on making that store-owner workflow faster and easier to manage from the moment inventory comes in.',
        item1Title: 'Built for high-volume resale inventory',
        item1Text: 'JustConsignIn is designed for consignment and resale stores that receive lots of unique items. Move quickly from an item in hand to a complete consignment record without relying on paper notes or spreadsheets.',
        item2Title: 'Consignor accounts',
        item2Text: 'Keep contact details, commission split, notes, balances and every item connected to the correct consignor.',
        item3Title: 'Fast mobile item intake',
        item3Text: 'Create consignors and add items from your phone while you are receiving inventory. Enter the item once, add product details and photos, and keep the intake process moving.',
        item4Title: 'Create Shopify products without duplicate entry',
        item4Text: 'Turn a consignment item into a Shopify product without typing the same information into a second system. Publish to Shopify POS and choose whether the item should also be available online.',
        item5Title: 'Shopify POS, online and manual sales tracking',
        item5Text: 'Keep each consignment item tied to the correct consignor whether it sells in-store through Shopify POS, through your Shopify online store, or through a manual sale workflow.',
        item6Title: 'Payout management',
        item6Text: 'See sold-unpaid items, calculate the consignor share and record payouts while preserving the full sale and payout history.',
        item7Title: 'Reports and transactions',
        item7Text: 'Review sales, consignor earnings, payout history and transaction activity from the same workspace so you always know what sold and what is still owed.',
        item8Title: 'Import and export for larger inventories',
        item8Text: 'Bulk import consignors and items from CSV and keep downloadable data tools available when you are moving existing inventory into JustConsignIn or maintaining your own records.',
      }),
      block('FeaturesAudienceBlock', 'features-audience', {
        eyebrow: 'Who JustConsignIn is for',
        heading: 'Shopify stores with a lot of unique resale inventory to enter and track.',
        text: 'The common problem is volume: many individual items, many consignors and a constant need to know who owns what, what sold and what each person is owed.',
        item1Title: 'Consignment & resale shops',
        item1Text: 'Stores taking in a steady flow of one-of-a-kind inventory from consignors.',
        item2Title: 'Secondhand & thrift-style stores',
        item2Text: 'Shops using Shopify that need a faster way to enter and manage large amounts of resale inventory tied to individual consignors.',
        item3Title: 'Children’s & family resale',
        item3Text: 'Clothing, toys, baby gear and other categories where many unique items can arrive from the same consignor at once.',
        item4Title: 'Vintage & clothing stores',
        item4Text: 'Apparel, accessories and vintage inventory where every item may need its own title, price, photos and consignor record.',
        item5Title: 'Furniture & home décor consignment',
        item5Text: 'Larger one-off pieces that need ownership, pricing, sale status and payout information kept together.',
        item6Title: 'Specialty resale stores',
        item6Text: 'Sporting goods, collectibles, designer goods and other resale businesses handling unique inventory through Shopify.',
      }),
      block('FeaturesCtaBlock', 'features-cta', {
        heading: 'Spend less time entering inventory and more time selling it.',
        text: 'Explore consignors, fast mobile intake, Shopify product creation, POS and online sales tracking, and payouts in the working app demo.',
        buttonText: 'Open Shopify App Demo',
        buttonUrl: '/shopify-app',
      }),
    ],
    root: { props: {} },
  },

  'how-it-works': {
    content: [
      hero(
        'how-hero',
        'How it works',
        'From consignment intake to Shopify sale to payout.',
        'Enter the consignor and item once. JustConsignIn carries that information through Shopify product creation, selling and the final consignor payout.'
      ),
      heading('how-01-title', '01 · Create the consignor'),
      text('how-01-copy', 'Add the consignor number, contact information, commission split and notes so every item stays tied to the right person.'),
      heading('how-02-title', '02 · Add the item from your phone'),
      text('how-02-copy', 'Enter the item details, asking price, condition and photo while you are receiving the inventory.'),
      heading('how-03-title', '03 · Create the Shopify product'),
      text('how-03-copy', 'Use the same intake record to create the Shopify product and publish it to Shopify POS, with optional online publishing when needed.'),
      heading('how-04-title', '04 · Sell through Shopify'),
      text('how-04-copy', 'Sell the product through Shopify POS or your connected sales workflow while JustConsignIn keeps the consignment record attached to the consignor.'),
      heading('how-05-title', '05 · Review what is owed'),
      text('how-05-copy', 'Sold-unpaid items appear in the payout workflow with the sale price, commission split and consignor share already connected.'),
      heading('how-06-title', '06 · Pay the consignor and keep the history'),
      text('how-06-copy', 'Record the payout method, date and included items. Sales, payouts and transaction history remain available for reporting.'),
      heading('how-problem-1', 'How to avoid duplicate entry when adding consignment products to Shopify'),
      text('how-problem-1-copy', 'Enter the item during intake, then use that same JustConsignIn record to create the Shopify product. The product details do not need to be maintained once in a spreadsheet and typed again later in Shopify.'),
      heading('how-problem-2', 'Streamlining consignment intake from your phone'),
      text('how-problem-2-copy', 'Add the consignor, item details and photos while inventory is being received. Mobile intake is designed to move the item directly into the Shopify product workflow without waiting for a separate desktop data-entry step.'),
      heading('how-problem-3', 'How to keep Shopify POS sales connected to consignor payouts'),
      text('how-problem-3-copy', 'Each item remains tied to its consignor. When the item sells through the connected Shopify workflow, the sale, commission split and amount owed can move into the sold-unpaid and payout workflow together.'),
      heading('how-problem-4', 'Managing one-of-a-kind consignment inventory without separate spreadsheets'),
      text('how-problem-4-copy', 'JustConsignIn keeps the item record, Shopify connection, sale status and payout history together so stores can follow individual consignment pieces without maintaining separate intake, sales and payout files.'),
      cta('how-cta', 'Run intake from the counter, floor or your phone.', 'The goal is simple: fewer spreadsheets, less duplicate entry and a clear connection between the Shopify product and the person who consigned it.', 'Open Shopify App Demo', '/shopify-app'),
    ],
    root: { props: {} },
  },

  pricing: {
    content: [
      hero(
        'pricing-hero',
        'Pricing',
        'JustConsignIn for Shopify includes a 14-day free trial.',
        'JustConsignIn brings consignors, Shopify product creation, POS sales and payouts into one workflow. Account onboarding is being finalized; the app demo is available now.'
      ),
      heading('pricing-plan-title', 'JustConsignIn for Shopify'),
      text('pricing-plan-price', '14-day free trial'),
      text('pricing-plan-note', 'The 14-day free trial will be available when account onboarding opens.'),
      heading('pricing-features-title', 'Included', 'h3'),
      text('pricing-features-copy', 'Consignor management · Mobile item intake · Create Shopify products · Shopify POS publishing · Optional online publishing · Manual sale tracking · Sales and payouts · Transactions and reports · CSV import / export'),
      text('pricing-plan-shopify-copy', 'Create products from your phone, publish to Shopify POS and keep each sale connected to the correct consignor.'),
      heading('pricing-advanced-title', 'Advanced', 'h3'),
      text('pricing-advanced-copy', 'Coming later. For larger operations that need additional locations and workflows.'),
    ],
    root: { props: {} },
  },

  contact: {
    content: [
      hero('contact-hero', 'Contact', 'Need help with JustConsignIn?', 'For support, account questions, setup help, or general inquiries, email us directly.'),
      heading('contact-email-title', 'Email support', 'h3'),
      text('contact-email-copy', 'support@justconsignin.com'),
      heading('contact-include-title', 'What to include', 'h3'),
      text('contact-include-copy', 'If you are reporting a problem, include the page you were on, what you were trying to do, and a screenshot if possible.'),
      heading('contact-response-title', 'Response', 'h3'),
      text('contact-response-copy', 'We will respond through the support email address you contact us from.'),
    ],
    root: { props: {} },
  },

  privacy: {
    content: [
      hero('privacy-hero', 'Privacy', 'Privacy policy', 'Last updated: August 2026'),
      heading('privacy-collect-title', 'Information we collect'),
      text('privacy-collect-copy', 'JustConsignIn processes account information such as your name, business name, email address and authentication information. When you use the service, you may also enter consignor contact information, inventory records, sale records, payout records, notes and business settings.'),
      heading('privacy-use-title', 'How we use information'),
      text('privacy-use-copy', 'We use information to provide and secure the service, maintain your workspace, calculate and record consignment activity, provide customer support, process subscriptions, prevent abuse and improve reliability.'),
      heading('privacy-providers-title', 'Service providers'),
      text('privacy-providers-copy', 'Production deployments may use hosting, database/authentication, payment and email providers. These providers process information only as needed to provide their services. Payment card details are handled by the payment provider and are not intended to be stored directly by JustConsignIn.'),
      heading('privacy-consignor-title', 'Your consignor data'),
      text('privacy-consignor-copy', 'You are responsible for having an appropriate basis to enter and use personal information belonging to your consignors. Do not enter sensitive information that is not necessary for consignment management.'),
      heading('privacy-retention-title', 'Retention and deletion'),
      text('privacy-retention-copy', 'Workspace information is retained while an account is active and for a reasonable period afterward when needed for recovery, fraud prevention, legal obligations or support. Account owners may request deletion of their account and workspace, subject to records we are required to retain.'),
      heading('privacy-security-title', 'Security'),
      text('privacy-security-copy', 'We use access controls, protected server credentials and third-party authentication/payment services designed to reduce unauthorized access. No online service can guarantee absolute security.'),
      heading('privacy-contact-title', 'Contact'),
      text('privacy-contact-copy', 'Privacy questions and deletion requests should be sent using the support contact published by JustConsignIn.'),
      text('privacy-launch-note', 'Launch draft: have this policy reviewed for the jurisdictions where you operate before accepting production customers.'),
    ],
    root: { props: {} },
  },

  terms: {
    content: [
      hero('terms-hero', 'Terms', 'Terms of service', 'Last updated: August 2026'),
      heading('terms-use-title', 'Using JustConsignIn'),
      text('terms-use-copy', 'You may use JustConsignIn to manage legitimate consignment and resale operations. You are responsible for the accuracy of information entered into your workspace, your staff’s access, and complying with laws that apply to your business and consignors.'),
      heading('terms-trial-title', '14-day free trial and subscriptions'),
      text('terms-trial-copy', 'New paid-plan signups may begin with a 14-day free trial. A valid payment method may be required to start the trial. Unless the subscription is cancelled before the trial ends, the selected recurring subscription will begin and the payment provider may charge the payment method on file according to the price shown at checkout.'),
      heading('terms-billing-title', 'Billing and cancellation'),
      text('terms-billing-copy', 'Subscriptions renew automatically until cancelled. Account owners can manage payment details and cancellation through the billing portal when production billing is enabled. Cancellation stops future renewal; access may continue through the end of the current paid or trial period depending on billing configuration. Fees already charged are non-refundable except where required by law or expressly stated otherwise.'),
      heading('terms-accounts-title', 'Accounts and security'),
      text('terms-accounts-copy', 'You must provide accurate account information and protect your login credentials. You are responsible for activity performed through your account and should notify support if you believe access has been compromised.'),
      heading('terms-acceptable-title', 'Acceptable use'),
      text('terms-acceptable-copy', 'Do not use the service to break the law, infringe rights, distribute malicious software, attempt unauthorized access, interfere with the service, or store information you do not have a lawful reason to process.'),
      heading('terms-availability-title', 'Availability and changes'),
      text('terms-availability-copy', 'We may update features, correct errors, perform maintenance, or change service availability. We aim to provide a reliable service but do not guarantee uninterrupted or error-free operation.'),
      heading('terms-data-title', 'Your data'),
      text('terms-data-copy', 'You retain responsibility for business and consignor information you enter. You grant JustConsignIn the limited rights necessary to host, process and back up that information to provide the service.'),
      heading('terms-termination-title', 'Termination'),
      text('terms-termination-copy', 'Accounts may be suspended or terminated for non-payment, abuse, security risk or material violation of these terms. You may stop using the service and cancel your subscription through the available billing controls.'),
      heading('terms-liability-title', 'Liability'),
      text('terms-liability-copy', 'To the extent permitted by law, JustConsignIn is provided without guarantees beyond those expressly stated, and liability is limited to the extent allowed by applicable law.'),
      text('terms-launch-note', 'Launch draft: have these terms reviewed for the jurisdictions where you operate and confirm the final price/refund policy before accepting production customers.'),
    ],
    root: { props: {} },
  },
};


const JUSTIN_PAGE_EDITOR_DATA = {
  home: {
    content: [
      block('ShowcaseHeroBlock', 'justin-home-showcase', {
        eyebrow: 'Developer • Product Builder • Problem Solver',
        heading: 'I build digital products that',
        accent: 'solve real problems.',
        text: 'Web applications, Shopify solutions, ecommerce systems, automation and AI-assisted development — from the first idea through testing, refinement and deployment.',
        primaryButtonText: 'View my work →',
        primaryButtonUrl: '/work',
        secondaryButtonText: 'How I work with AI',
        secondaryButtonUrl: '/ai-development',
        note: 'Based in Ontario, Canada • Building real products for real business workflows',
        cardBadge: 'FEATURED PROJECT',
        cardTitle: 'JustConsignIn — Shopify consignment management built from a real store problem.',
        cardText: 'A working product connecting consignors, inventory, Shopify products, POS sales and payouts.',
        flow1: 'Intake', flow2: 'Shopify', flow3: 'Sold', flow4: 'Paid',
      }),
      block('ProofStripBlock', 'justin-home-proof', {
        item1Title: 'Real products', item1Text: 'Not mockups built only for a portfolio.',
        item2Title: 'Real workflows', item2Text: 'Software designed around actual business needs.',
        item3Title: 'AI-assisted', item3Text: 'Faster prototyping, debugging, iteration and delivery.',
      }),
      block('CaseStudyBlock', 'justin-home-case-study', {
        eyebrow: 'Featured case study',
        sectionHeading: 'From a real store problem to a working Shopify product.',
        sectionText: 'JustConsignIn started with a real consignment workflow at Jill & The Beanstalk and grew into a Shopify-focused application for managing consignors, products, sales and payouts.',
        projectEyebrow: 'JustConsignIn',
        projectHeading: 'Build around the business. Not the other way around.',
        projectText: 'The goal was not to build another spreadsheet. It was to remove duplicate entry, connect consignment inventory to Shopify, support mobile intake, track sold items and make consignor payouts easier to understand.',
        tags: 'Shopify, React, POS, Supabase, Mobile Intake, Payouts',
        buttonText: 'Read the story →', buttonUrl: '/work',
        workflowTitle: 'Consignment workflow',
        step1: 'Create consignor + item',
        step2: 'Publish to Shopify POS / Online Store',
        step3: 'Track the sale back to the consignor',
        step4: 'Calculate and complete payout',
      }),
      block('CardGridBlock', 'justin-home-work-grid', {
        item1Eyebrow:'Professional work',item1Title:'Wheels Automotive',item1Text:'Adobe Commerce / Magento, B2B ecommerce, frontend components, QA, product/category content, SEO and launch support.',item1Icon:'WA',item1Style:'dark',
        item2Eyebrow:'Custom business tools',item2Title:'Internal tools & admin systems',item2Text:'Dashboards, data-entry workflows, admin tools and interfaces designed around how people actually perform the work.',item2Icon:'UI',item2Style:'white',
        item3Eyebrow:'Ecommerce',item3Title:'Shopify & commerce integrations',item3Text:'Product workflows, POS-connected applications, publishing controls and custom ecommerce experiences.',item3Icon:'EC',item3Style:'blue',
        item4Eyebrow:'AI-assisted development',item4Title:'From idea to working software faster.',item4Text:'AI supports architecture, prototyping, debugging, refactoring, UX exploration, research and documentation while product direction stays human-led.',item4Icon:'AI',item4Style:'white',
      }),
      block('StorySplitBlock', 'justin-home-story', {
        leftEyebrow:'About me',leftHeading:'I didn’t start my career behind a laptop.',
        leftText1:'My background is in mechanical engineering technology, CNC programming and tool & die design. That taught me to think about systems, tolerances, workflows and how things actually have to work in the real world.',
        leftText2:'I brought that same problem-solving mindset into web and mobile development.',
        rightEyebrow:'How I think',rightHeading:'Software should remove friction, not create more of it.',
        point1Title:'Understand the workflow first',point1Text:'Before writing code, I want to know what people are doing today, what is repetitive and where the process breaks down.',
        point2Title:'Build the simplest useful version',point2Text:'I would rather test a useful working flow early than spend months polishing the wrong solution.',
        point3Title:'Connect the systems already in use',point3Text:'Shopify, POS, APIs, databases and internal tools should work together instead of creating more duplicate work.',
        point4Title:'Keep changing the product when reality says it should change',point4Text:'Real usage exposes things a specification never will. The software should evolve around what users actually need.',
      }),
      block('ProcessRowsBlock', 'justin-home-ai-process', {
        eyebrow:'AI + Development',heading:'AI changes what one developer can accomplish.',
        text:'I use AI throughout the development process — not as a replacement for judgment, but as a way to move faster across more parts of a project.',
        note:'The business problem, product decisions, testing and final direction still need a human who understands what the software is supposed to accomplish.',
        row1Label:'RESEARCH',row1Text:'Explore technologies, approaches and business requirements quickly.',
        row2Label:'ARCHITECTURE',row2Text:'Break a product into workflows, data structures and technical components.',
        row3Label:'BUILD',row3Text:'Accelerate frontend, backend, integrations and rapid prototyping.',
        row4Label:'DEBUG',row4Text:'Investigate problems, compare approaches and iterate much faster.',
        row5Label:'REFINE',row5Text:'Improve UX, documentation, SEO, content and deployment workflows.',
      }),
      block('SkillsGridBlock', 'justin-home-skills', {
        eyebrow:'Technology',heading:'Tools I use to ship real work.',
        text:'I prefer showing technologies in the context of what I actually build rather than treating a skills list as the portfolio itself.',
        item1Title:'Frontend',item1Text:'HTML, CSS, JavaScript, React, Angular, TypeScript, responsive UI and mobile-first design.',
        item2Title:'Backend & Data',item2Text:'Node, Express, PHP, MySQL, Supabase, REST APIs and data-driven application workflows.',
        item3Title:'Commerce',item3Text:'Shopify, Shopify POS, Adobe Commerce / Magento, WordPress and ecommerce product workflows.',
        item4Title:'Delivery',item4Text:'Git, GitHub, Vercel, Linux, QA, deployment, SEO, analytics and AI-assisted development.',
      }),
      block('LargeCtaBlock', 'justin-home-large-cta', {
        eyebrow:'Open to the right opportunity',
        heading:'Need someone who can understand the problem and build the solution?',
        buttonText:'Get in touch →',
        buttonUrl:'/contact',
      }),
    ],
    root: { props: {} },
  },
  work: {
    content: [
      hero('justin-work-hero', 'Selected Work', 'Projects built around real workflows.', 'Case studies covering product development, ecommerce, Shopify, internal tools and AI-assisted development.'),
      heading('justin-work-jci', 'JustConsignIn'),
      text('justin-work-jci-copy', 'Shopify consignment management application covering intake, product creation, POS sales, consignor tracking and payouts.'),
      heading('justin-work-wheels', 'Wheels Automotive'),
      text('justin-work-wheels-copy', 'Adobe Commerce / Magento B2B ecommerce, frontend implementation, QA, SEO and dealership-product workflows.'),
    ],
    root: { props: {} },
  },
  'ai-development': {
    content: [
      hero('justin-ai-hero', 'AI + Development', 'AI is part of the workflow, not the product pitch.', 'The focus is on what becomes possible when AI is combined with domain knowledge, product decisions, software development and constant testing.'),
      heading('justin-ai-problem', 'Start with a real problem'),
      text('justin-ai-problem-copy', 'The process begins with understanding the workflow, constraints and people using the system before choosing technology or generating code.'),
      heading('justin-ai-build', 'Use AI to accelerate iteration'),
      text('justin-ai-build-copy', 'AI helps research approaches, reason through architecture, generate and refactor code, inspect failures and iterate faster. The system still has to be tested against the actual requirement.'),
      heading('justin-ai-result', 'Ship something that works'),
      text('justin-ai-result-copy', 'The value is not the prompt. The value is turning a business problem into a maintainable product that people can actually use.'),
    ],
    root: { props: {} },
  },
  about: {
    content: [
      hero('justin-about-hero', 'About', 'Engineering experience translated into software development.', 'My background began in mechanical engineering, CNC machining, programming and tool & die design before retraining in web and mobile development.'),
      heading('justin-about-approach', 'How I approach development'),
      text('justin-about-approach-copy', 'I tend to work from the process backward: understand what someone is actually trying to accomplish, remove unnecessary steps, then build the interface and system around that workflow.'),
    ],
    root: { props: {} },
  },
  experience: {
    content: [
      hero('justin-experience-hero', 'Experience', 'Web, mobile, ecommerce and product development.', 'React, JavaScript, TypeScript, Node, PHP, MySQL, WordPress, Shopify, Adobe Commerce and mobile development backed by an engineering and manufacturing background.'),
      heading('justin-experience-wheels', 'Wheels Automotive Dealers Supply'),
      text('justin-experience-wheels-copy', 'B2B ecommerce launch work, Adobe Commerce / Magento frontend implementation, QA, content, SEO and vendor coordination.'),
      heading('justin-experience-product', 'Independent product development'),
      text('justin-experience-product-copy', 'Designing and building JustConsignIn from a real consignment-store workflow through Shopify integration, admin tooling, deployment and product marketing.'),
    ],
    root: { props: {} },
  },
  contact: {
    content: [
      hero('justin-contact-hero', 'Contact', 'Looking for a developer who understands both the code and the workflow?', 'Open to development roles, ecommerce work, product collaboration and selected freelance projects.'),
      cta('justin-contact-cta', 'Start a conversation.', 'Use the contact details on the finished site to reach out about a role or project.', 'Get in touch', '#contact'),
    ],
    root: { props: {} },
  },
};

export function getInitialPageBuilderData(id, siteKey = 'justconsignin') {
  const source = siteKey === 'justindematteis' ? JUSTIN_PAGE_EDITOR_DATA : PAGE_EDITOR_DATA;
  return source[id] || { content: [], root: { props: {} } };
}
